import type { Test } from "./index";

const test: Test = {
  id: "oir-8",
  title: "OIR Test 8",
  durationMinutes: 20,
  questions: [
    { q: "Find the next number: 3, 6, 11, 18, 27, ?", options: ["36", "38", "40", "42"], answer: 1, explanation: "Differences increase by 2 each time (3, 5, 7, 9, 11): 27+11 = 38." },
    { q: "Find the missing number: 5, 10, 20, 40, ?, 160", options: ["60", "80", "100", "120"], answer: 1, explanation: "Each term doubles the previous one: 40×2 = 80." },
    { q: "Find the missing number: 121, 100, 81, 64, ?, 36", options: ["49", "50", "56", "42"], answer: 0, explanation: "These are squares of consecutive descending integers (11², 10², 9², 8², 7², 6²); the missing term is 7² = 49." },
    { q: "Find the next number: 2, 5, 11, 23, 47, ?", options: ["93", "95", "97", "99"], answer: 1, explanation: "Each term equals double the previous term plus 1: 47×2+1 = 95." },
    { q: "Find the next letter: Z, W, T, Q, ?", options: ["M", "N", "O", "P"], answer: 1, explanation: "Each letter steps back 3 positions in the alphabet: Q (17th) − 3 = 14th letter, N." },
    { q: "Find the next pair: AY, CW, EU, GS, ?", options: ["IQ", "HR", "IR", "JQ"], answer: 0, explanation: "First letters advance by 2 (A, C, E, G, I) while second letters retreat by 2 (Y, W, U, S, Q), giving IQ." },
    { q: "Bread : Baker :: Furniture : ?", options: ["Carpenter", "Mason", "Cobbler", "Tailor"], answer: 0, explanation: "A Baker makes Bread; a Carpenter makes Furniture." },
    { q: "25 : 125 :: 36 : ?", options: ["196", "216", "256", "144"], answer: 1, explanation: "The relationship is a number squared paired with its cube: 5²=25 and 5³=125, so 6²=36 pairs with 6³=216." },
    { q: "Peninsula : Water :: Oasis : ?", options: ["Desert", "Forest", "Mountain", "Sea"], answer: 0, explanation: "A Peninsula is surrounded by Water; an Oasis is a fertile spot found within a Desert." },
    { q: "Which one does not belong with the others?", options: ["Sparrow", "Crow", "Bat", "Parrot"], answer: 2, explanation: "Sparrow, Crow and Parrot are birds; a Bat is a mammal." },
    { q: "Which number does not belong with the others?", options: ["13", "17", "23", "27"], answer: 3, explanation: "13, 17 and 23 are prime numbers; 27 (= 3³) is not." },
    { q: "Which one does not belong with the others?", options: ["Kilometre", "Metre", "Litre", "Centimetre"], answer: 2, explanation: "Kilometre, Metre and Centimetre are units of length; Litre measures volume." },
    { q: "If DELHI is coded as CDKGH, how is MUMBAI coded?", options: ["LTLAZH", "LTLAZI", "LTMAZH", "KTLAZH"], answer: 0, explanation: "Each letter shifts one place back in the alphabet (D→C, E→D, L→K, H→G, I→H); applying this to MUMBAI gives LTLAZH." },
    { q: "If ZEBRA is written as 2652181 (using letter positions), how is COBRA written?", options: ["3152181", "3151281", "3152182", "2152181"], answer: 0, explanation: "Using letter positions (C=3, O=15, B=2, R=18, A=1) and concatenating the numbers gives 3152181." },
    { q: "In a code language, 'ne ki pa' means 'you are good', 'ki lo' means 'good boy' and 'pa ti' means 'you go'. What is the code for 'are'?", options: ["ne", "ki", "pa", "lo"], answer: 0, explanation: "'ki' (common to sentences 1 and 2) codes 'good' and 'pa' (common to sentences 1 and 3) codes 'you', leaving 'ne' to code 'are'." },
    { q: "P is the daughter of Q. Q is the brother of R. R is the wife of S. How is P related to S?", options: ["Niece", "Daughter", "Sister-in-law", "Cousin"], answer: 0, explanation: "R is S's wife and Q's sister; P, being Q's daughter, is therefore S's niece." },
    { q: "Rahul's mother is the only daughter of Sunil's father. How is Sunil related to Rahul?", options: ["Maternal uncle", "Father", "Brother", "Cousin"], answer: 0, explanation: "Rahul's mother is Sunil's father's only daughter, making her Sunil's sister — so Sunil is Rahul's maternal uncle." },
    { q: "A boy walks 6 km west and then 8 km north. What is the shortest distance back to his starting point?", options: ["10 km", "12 km", "14 km", "2 km"], answer: 0, explanation: "The straight-line distance is the hypotenuse of a 6-8 right triangle: √(6²+8²) = 10 km." },
    { q: "If North-West becomes South, what does East become?", options: ["North-West", "South-West", "North-East", "South"], answer: 0, explanation: "The mapping rotates each direction 225° clockwise: North-West (315°) → South (180°) confirms this, and applying it to East (90°) gives 315°, North-West." },
    { q: "In a row of 30 students, Neha is 12th from the left and Rekha is 8th from the right. How many students are between them?", options: ["9", "10", "11", "12"], answer: 1, explanation: "Rekha's position from the left is 30−8+1 = 23; students strictly between positions 12 and 23 number 23−12−1 = 10." },
    { q: "B is heavier than A but lighter than C. D is heavier than C. E is lighter than A. Who is the third heaviest?", options: ["B", "C", "A", "D"], answer: 0, explanation: "The order from heaviest to lightest is D > C > B > A > E, making B the third heaviest." },
    { q: "What is the value of 15% of 40 + 40% of 15?", options: ["10", "12", "14", "16"], answer: 1, explanation: "15% of 40 = 6 and 40% of 15 = 6, so the sum is 12." },
    { q: "A number is doubled and 9 is added. The result is then trebled to give 75. What is the number?", options: ["6", "8", "10", "12"], answer: 1, explanation: "(2x+9)×3 = 75 gives 2x+9 = 25, so x = 8." },
    { q: "What is the angle between the hands of a clock at 9:45?", options: ["15°", "22.5°", "30°", "7.5°"], answer: 1, explanation: "Using |30H − 5.5M|: |30×9 − 5.5×45| = |270 − 247.5| = 22.5°." },
    { q: "26 January 2026 is a Monday. What day of the week is 15 August 2026?", options: ["Friday", "Saturday", "Sunday", "Monday"], answer: 1, explanation: "From 26 Jan to 15 Aug 2026 is 201 days; 201 mod 7 = 5, so Monday + 5 days = Saturday." },
    { q: "Statements: Some books are pens. No pen is a pencil. Conclusions: I. Some books are not pencils. II. No book is a pencil.", options: ["Only I follows", "Only II follows", "Both follow", "Neither follows"], answer: 0, explanation: "The books that are pens can't be pencils since no pen is a pencil, so 'some books are not pencils' follows; but nothing rules out other books being pencils, so II doesn't follow." },
    { q: "Statement: Road accidents in the city have increased sharply. Courses of action: I. Traffic rules should be enforced strictly. II. All roads in the city should be closed.", options: ["Only I follows", "Only II follows", "Both follow", "Neither follows"], answer: 0, explanation: "Enforcing traffic rules is a practical response to rising accidents, while closing all roads is an impractical overreaction, so only I follows." },
    { q: "A 3 × 3 × 3 cube is painted on all faces and cut into 27 unit cubes. How many unit cubes have at least two faces painted?", options: ["12", "20", "26", "8"], answer: 1, explanation: "8 corner cubes have three painted faces and 12 edge cubes have two, giving 8+12 = 20 cubes with at least two faces painted." },
    { q: "Which letter is 3rd to the left of the letter that is 9th to the right of E in the English alphabet?", options: ["K", "L", "J", "M"], answer: 0, explanation: "E is the 5th letter; 9th to its right is the 14th letter (N), and 3rd to the left of N is the 11th letter, K." },
    { q: "How many pairs of letters in the word BRIGADE are consecutive letters of the alphabet (in either order, not necessarily adjacent in the word)?", options: ["1", "2", "3", "4"], answer: 1, explanation: "The letters are B, R, I, G, A, D, E; only (A,B) and (D,E) differ by one alphabet position, giving 2 consecutive pairs." },
  ],
};

export default test;
