import type { Test } from "./index";

const test: Test = {
  id: "oir-96",
  title: "OIR Test 96",
  durationMinutes: 20,
  releaseAt: "2027-01-17T00:00:00+05:30",
  questions: [
    { q: "Find the next number: 14256, 2376, 396, 66, ?", options: ["11", "9", "55", "12"], answer: 0, explanation: "Here each term is the previous term divided by 6. Next: 66 ÷ 6 = 11." },
    { q: "Find the next number: 27, 29, 33, 39, 41, ?", options: ["43", "48", "49", "47"], answer: 3, explanation: "Here the terms are consecutive prime numbers plus 10. Next: 37 + 10 = 47." },
    { q: "Find the next number: 9, 10, 14, 21, 31, ?", options: ["43", "47", "41", "44"], answer: 3, explanation: "Here the differences added are 1, 4, 7, 10, 13 — each 3 more than the last. Next: 31 + 13 = 44." },
    { q: "Find the missing number: 15, 19, 31, ?, 175, 499", options: ["103", "77", "67", "139"], answer: 2, explanation: "Here the differences 4, 12, 36, 108, 324 are each 3 times the previous difference, so the missing term is 67." },
    { q: "Find the next letter: E, F, K, L, Q, ?", options: ["R", "S", "Q", "T"], answer: 0, explanation: "By alphabet positions (5, 6, 11, 12, 17), the letters move alternately +1 and +5: Q(17) + 1 = R(18)." },
    { q: "Find the next pair: GM, IL, KK, MJ, ?", options: ["OH", "PI", "OI", "NH"], answer: 2, explanation: "The first letters move 2 forward each time and the second letters move 1 back: next is OI." },
    { q: "Architect : Building :: Cartographer : ?", options: ["Road", "Ship", "Map", "Bridge"], answer: 2, explanation: "An architect designs buildings; a cartographer draws maps." },
    { q: "9 : 162 :: 2 : ?", options: ["9", "4", "8", "7"], answer: 2, explanation: "9 → 2 × 9² = 162; likewise 2 → 2 × 2² = 8." },
    { q: "Himalayas : Young fold mountains :: Aravallis : ?", options: ["Old fold mountains", "Volcanic mountains", "Young fold mountains", "Block mountains"], answer: 0, explanation: "The Himalayas are young fold mountains; the Aravallis are among the oldest fold mountains." },
    { q: "Which one does not belong with the others?", options: ["Potter", "Carpenter", "Teacher", "Blacksmith"], answer: 2, explanation: "A teacher is not an artisan who makes things by hand." },
    { q: "Which number does not belong with the others?", options: ["143", "81", "16", "144"], answer: 0, explanation: "144 = 12², 81 = 9², 16 = 4² are perfect squares; 143 is not." },
    { q: "Choose the one word for: \"A person with long experience, especially a former soldier\"", options: ["Cadet", "Novice", "Recruit", "Veteran"], answer: 3, explanation: "Veteran: a person with long experience, especially a former soldier." },
    { q: "If TEAM is written as 20-5-1-13, how is RIFLE written in the same code?", options: ["18-9-6-12-5", "18-10-6-12-5", "18-9-5-12-5", "9-18-21-15-22"], answer: 0, explanation: "Each letter is replaced by its position in the alphabet (A = 1, …, Z = 26), so RIFLE → 18-9-6-12-5." },
    { q: "In a code language, 'loyal leaders work' is written as 'ga si pi', 'young leaders' is written as 'fe ga' and 'work daily' is written as 'pi tu'. What is the code for 'loyal'?", options: ["si", "fe", "pi", "ga"], answer: 0, explanation: "'leaders' is common to the first two sentences, so leaders = ga; 'work' is common to the first and third, so work = pi. The remaining code in the first sentence, si, means 'loyal'." },
    { q: "If A = 1, B = 2, …, Z = 26 and COLLEGE = 59 (the sum of its letter values), what is DONKEY?", options: ["78", "74", "88", "84"], answer: 1, explanation: "DONKEY = 4 + 15 + 14 + 11 + 5 + 25 = 74." },
    { q: "Pinky is Rohit's daughter. Rohit is Sachin's only brother. Sachin's wife is Tina. How is Tina related to Pinky?", options: ["Grandmother", "Mother", "Sister", "Aunt"], answer: 3, explanation: "Sachin is Pinky's uncle, so his wife Tina is her aunt." },
    { q: "Pointing to a girl, Mridul said, \"Her father's father is my mother's husband, and I am my parents' only child.\" How is the girl related to Mridul?", options: ["Sister", "Niece", "Granddaughter", "Daughter"], answer: 3, explanation: "The girl's grandfather is Mridul's father; as Mridul is the only child, the girl must be Mridul's daughter." },
    { q: "Starting from his house, Rohit walks 1 km towards the south, turns right and walks 4 km, turns left and walks 14 km, finally turns left and walks 14 km. In which direction is he now from his house?", options: ["South-East", "North-West", "North-East", "South-West"], answer: 0, explanation: "He ends up 10 km east and 15 km south of his house, so he is to the South-East of his house." },
    { q: "A man is facing North-East. He turns 90° anticlockwise, then 90° clockwise, then 90° anticlockwise. Which direction is he facing now?", options: ["North-East", "North-West", "South-East", "South-West"], answer: 1, explanation: "The net turn is 90° anticlockwise from North-East, so he faces North-West." },
    { q: "In a class of 49 students, Ravi ranks 7th from the top. What is his rank from the bottom?", options: ["42nd", "44th", "45th", "43rd"], answer: 3, explanation: "Rank from bottom = 49 − 7 + 1 = 43." },
    { q: "Farhan is heavier than Lata. Chetan is lighter than Lata. Ravi is lighter than Chetan. Asha is lighter than Ravi. Who is the second heaviest?", options: ["Ravi", "Chetan", "Farhan", "Lata"], answer: 3, explanation: "The order from heaviest to lightest is Farhan > Lata > Chetan > Ravi > Asha, so the second heaviest is Lata." },
    { q: "The sum of 3 consecutive odd numbers is 141. What is the largest of them?", options: ["49", "51", "45", "47"], answer: 0, explanation: "The middle value is 141/3 = 47; the numbers are 45, 47, 49, so the largest is 49." },
    { q: "A boat goes 14 km downstream in 1 hour and 8 km upstream in 1 hour. What is the speed of the boat in still water?", options: ["6 km/h", "3 km/h", "11 km/h", "12 km/h"], answer: 2, explanation: "Boat speed = (14 + 8)/2 = 11 km/h; stream speed = (14 − 8)/2 = 3 km/h." },
    { q: "A clock loses 5 minutes every hour. It is set right at 6 am. What time will it show when the correct time is 10:00 am the same day?", options: ["9:45 am", "10:20 am", "9:35 am", "9:40 am"], answer: 3, explanation: "In 4 hours it loses 5 × 4 = 20 minutes, so it shows 9:40 am." },
    { q: "Which year will have exactly the same calendar as 2036?", options: ["2063", "2040", "2065", "2064"], answer: 3, explanation: "A year has the same calendar when it starts on the same weekday and is also a leap year. Counting odd days (1 per ordinary year, 2 per leap year) from 2036 until they total a multiple of 7 gives 2064." },
    { q: "Statements: All clouds are doctors. No plate is a doctor. Conclusions: I. No cloud is a plate. II. All plates are clouds.", options: ["Only I follows", "Only II follows", "Both follow", "Neither follows"], answer: 0, explanation: "All clouds are doctors and no a plate is a doctor, so no a cloud is a plate (I); II contradicts this." },
    { q: "Statement: A soldier on sentry duty was found asleep. Courses of action: I. Disciplinary action should be taken against him as per the rules. II. Sentry duty should be abolished. Which course(s) of action follow?", options: ["Only I follows", "Only II follows", "Both follow", "Neither follows"], answer: 0, explanation: "Disciplining the individual is appropriate (I); sentry duty is essential and cannot be abolished." },
    { q: "A wooden block measuring 6 cm × 5 cm × 3 cm is painted on all faces and cut into 1 cm cubes. How many cubes have no face painted?", options: ["8", "12", "38", "32"], answer: 1, explanation: "Cubes with no face painted: (6 − 2)(5 − 2)(3 − 2) = 12." },
    { q: "Which letter is 18th to the right of the 6th letter from the left in the English alphabet?", options: ["W", "Y", "V", "X"], answer: 3, explanation: "The 6th letter from the left is F; 18 places to its right is the 24th letter, X." },
    { q: "If the letters of the word MONSOON are arranged in alphabetical order, how many letters remain in the same position?", options: ["4", "5", "3", "6"], answer: 0, explanation: "Alphabetical order: MNNOOOS. Comparing with MONSOON, 4 letters (M, N, O, O) stay in place." },
  ],
};

export default test;
