import type { Test } from "./index";

const test: Test = {
  id: "oir-3",
  title: "OIR Test 3",
  durationMinutes: 20,
  questions: [
    { q: "Find the next number: 6, 11, 21, 41, 81, ?", options: ["151", "161", "171", "181"], answer: 1, explanation: "Each difference doubles the previous one (5, 10, 20, 40, 80): 81+80 = 161." },
    { q: "Find the next number: 3, 8, 15, 24, 35, ?", options: ["46", "47", "48", "49"], answer: 2, explanation: "The differences increase by 2 each time (5, 7, 9, 11, 13): 35+13 = 48." },
    { q: "Find the next number: 720, 120, 24, 6, 2, ?", options: ["0", "1", "2", "3"], answer: 1, explanation: "Each term is divided by a decreasing factor (6, 5, 4, 3, 2): 2÷2 = 1." },
    { q: "Find the missing number: 2, 6, 18, 54, ?, 486", options: ["108", "162", "216", "324"], answer: 1, explanation: "Each term is multiplied by 3: 54×3 = 162, and 162×3 = 486 confirms it." },
    { q: "Find the next letter: C, F, I, L, O, ?", options: ["Q", "R", "S", "T"], answer: 1, explanation: "Each letter advances 3 positions (C, F, I, L, O, ...): O (15th) + 3 = 18th letter, R." },
    { q: "Find the next pair: ZA, YB, XC, WD, ?", options: ["VE", "UE", "VF", "UF"], answer: 0, explanation: "The first letter steps backward (Z, Y, X, W, V) while the second steps forward (A, B, C, D, E), giving VE." },
    { q: "Hour : Minute :: Minute : ?", options: ["Hour", "Second", "Day", "Time"], answer: 1, explanation: "An hour is divided into minutes, just as a minute is divided into seconds." },
    { q: "3 : 27 :: 5 : ?", options: ["25", "75", "125", "150"], answer: 2, explanation: "The relationship is a number cubed: 3³ = 27, so 5³ = 125." },
    { q: "Cricket : Pitch :: Boxing : ?", options: ["Ring", "Court", "Arena", "Field"], answer: 0, explanation: "Cricket is played on a pitch, just as boxing takes place in a ring." },
    { q: "Which one does not belong with the others?", options: ["Square", "Rectangle", "Rhombus", "Circle"], answer: 3, explanation: "Square, Rectangle and Rhombus are straight-sided polygons; a Circle has no sides or vertices." },
    { q: "Which number does not belong with the others?", options: ["15", "21", "28", "34"], answer: 3, explanation: "15, 21 and 28 are triangular numbers (n(n+1)/2 for n=5, 6, 7); 34 is not, since the next triangular number is 36." },
    { q: "Which one does not belong with the others?", options: ["Mango", "Banana", "Apple", "Potato"], answer: 3, explanation: "Mango, Banana and Apple are fruits; Potato is a vegetable (tuber)." },
    { q: "If each letter is given its position in the alphabet (A=1, B=2, ...) and CHAIR is coded as 39, what is the code for TABLE?", options: ["38", "39", "40", "41"], answer: 2, explanation: "Each word's code is the sum of its letters' positions: CHAIR = 3+8+1+9+18 = 39, so TABLE = 20+1+2+12+5 = 40." },
    { q: "If GOLD is written as HQOH, how is IRON written in the same code?", options: ["JTRR", "JTRQ", "JSRR", "JTQR"], answer: 0, explanation: "Each letter shifts forward by its position in the word (+1, +2, +3, +4): I+1=J, R+2=T, O+3=R, N+4=R, giving JTRR." },
    { q: "In a code language, 'ki pa lo' means 'we are brave', 'pa ma' means 'brave men' and 'lo ti' means 'we fight'. Which word stands for 'are'?", options: ["ki", "pa", "lo", "ma"], answer: 0, explanation: "'pa' is the word shared with 'brave' and 'lo' is shared with 'we', leaving 'ki' to mean 'are'." },
    { q: "A's father is B's son. C is B's father. How is A related to C?", options: ["Grandson", "Great-grandchild", "Nephew", "Son"], answer: 1, explanation: "A's father is B's son, so B is A's grandparent; C is B's father, making C A's great-grandparent, so A is C's great-grandchild." },
    { q: "A man X says, \"Y's mother is the only daughter of my mother-in-law.\" How is X related to Y?", options: ["Father", "Uncle", "Brother", "Grandfather"], answer: 0, explanation: "The only daughter of X's mother-in-law is X's own wife, so Y's mother is X's wife — making X the father of Y." },
    { q: "A man walks 4 km east and then 3 km north. What is the shortest distance from his starting point?", options: ["5 km", "6 km", "7 km", "1 km"], answer: 0, explanation: "The two legs form a right triangle, so the direct distance is √(4²+3²) = 5 km." },
    { q: "A is 20 m north of B. C is 20 m east of A. D is 20 m south of C. In which direction is D from B?", options: ["East", "West", "North-East", "South-East"], answer: 0, explanation: "Plotting the points, the north and south legs cancel out, leaving D exactly 20 m east of B." },
    { q: "In a row of boys, Deepak is 7th from the left and Nilesh is 12th from the right. If they interchange positions, Deepak becomes 22nd from the left. How many boys are in the row?", options: ["31", "32", "33", "34"], answer: 2, explanation: "After swapping, Deepak occupies Nilesh's original spot (12th from right), which is now 22nd from left, so total boys = 22+12−1 = 33." },
    { q: "In a race, P finished before Q but after R. S finished after Q but before T. Who came last?", options: ["Q", "S", "T", "P"], answer: 2, explanation: "Combining R before P before Q, and Q before S before T, gives the order R, P, Q, S, T — so T finished last." },
    { q: "The average of 5 numbers is 20. When one number is removed, the average becomes 18. Which number was removed?", options: ["26", "28", "30", "32"], answer: 1, explanation: "The total of 5 numbers is 100 and the total of the remaining 4 is 72, so the removed number is 100−72 = 28." },
    { q: "A father is three times as old as his son. In 12 years he will be twice as old. What is the son's present age?", options: ["10", "12", "14", "16"], answer: 1, explanation: "Solving F=3S and F+12=2(S+12) gives S=12." },
    { q: "At what time between 3 and 4 o'clock do the hands of a clock coincide?", options: ["3:15", "3:16 4/11", "3:17 1/2", "3:18"], answer: 1, explanation: "Starting at 3:00 the hour hand is 15 minute-spaces ahead, and the minute hand gains on it at 5.5 min/min, so they meet after 15÷5.5 = 16 4/11 minutes, at 3:16 4/11." },
    { q: "15 August 2025 is a Friday. What day of the week was 26 January 2025?", options: ["Saturday", "Sunday", "Monday", "Tuesday"], answer: 1, explanation: "Aug 15 falls 201 days after Jan 26; 201 mod 7 = 5, so counting back 5 weekdays from Friday gives Sunday." },
    { q: "Statements: Some cats are dogs. All dogs are birds. Conclusions: I. Some cats are birds. II. All birds are dogs.", options: ["Only I follows", "Only II follows", "Both follow", "Neither follows"], answer: 0, explanation: "Since some cats are dogs and all dogs are birds, those cats must be birds (I follows); the reverse, that all birds are dogs, isn't guaranteed." },
    { q: "Statement: The government has banned single-use plastic. Conclusions: I. People will stop using all plastic entirely. II. Alternatives to single-use plastic will be needed.", options: ["Only I follows", "Only II follows", "Both follow", "Neither follows"], answer: 1, explanation: "Banning single-use plastic doesn't ban all plastic (I is an overreach), but it naturally creates demand for alternatives (II follows)." },
    { q: "A cube of side 5 cm is painted on all faces and cut into 1 cm cubes. How many small cubes have no face painted?", options: ["9", "27", "36", "64"], answer: 1, explanation: "Unpainted cubes lie strictly inside the cube: (n−2)³ = (5−2)³ = 27." },
    { q: "How many letters are there between the 8th letter from the left and the 8th letter from the right in the English alphabet?", options: ["9", "10", "11", "12"], answer: 1, explanation: "The 8th letter from the left is H, and the 8th from the right is S (26−8+1=19th); letters strictly between them number 19−8−1 = 10." },
    { q: "Which of the following words cannot be formed using only the letters of the word ADMINISTRATION?", options: ["STATION", "TRADITION", "MINISTER", "STRAIN"], answer: 2, explanation: "ADMINISTRATION contains no letter E, but MINISTER requires an E, so it cannot be formed from those letters." },
  ],
};

export default test;
