import type { Test } from "./index";

const test: Test = {
  id: "oir-10",
  title: "OIR Test 10",
  durationMinutes: 20,
  questions: [
    { q: "Find the next number: 2, 7, 17, 37, 77, ?", options: ["147", "155", "157", "167"], answer: 2, explanation: "Each difference doubles the previous one (5, 10, 20, 40, 80): 77+80 = 157." },
    { q: "Find the next number: 0, 3, 8, 15, 24, ?", options: ["33", "35", "37", "39"], answer: 1, explanation: "Each term equals n²−1 for n = 1, 2, 3, ...: 6²−1 = 35." },
    { q: "Find the next number: 1000, 500, 250, 125, ?", options: ["60", "62.5", "65", "75"], answer: 1, explanation: "Each term is half the previous term: 125/2 = 62.5." },
    { q: "Find the next number: 5, 6, 8, 11, 15, 20, ?", options: ["24", "25", "26", "27"], answer: 2, explanation: "The differences increase by 1 each time (1, 2, 3, 4, 5, 6): 20+6 = 26." },
    { q: "Find the next letter: A, E, I, M, Q, ?", options: ["T", "U", "V", "W"], answer: 1, explanation: "Each letter is 4 positions after the previous one: Q (17th) + 4 = 21st letter, U." },
    { q: "Find the next pair: CE, GI, KM, OQ, ?", options: ["RT", "SU", "TV", "QS"], answer: 1, explanation: "Both letters advance 4 positions from the previous pair: O(15)+4=19=S and Q(17)+4=21=U, giving 'SU'." },
    { q: "Grain : Granary :: Water : ?", options: ["Reservoir", "River", "Well", "Tap"], answer: 0, explanation: "A granary is where grain is stored; a reservoir is where water is stored." },
    { q: "14 : 196 :: 17 : ?", options: ["269", "279", "289", "299"], answer: 2, explanation: "The relationship is a number squared: 14² = 196, so 17² = 289." },
    { q: "Kolkata : Hooghly :: Delhi : ?", options: ["Ganga", "Yamuna", "Sutlej", "Gomti"], answer: 1, explanation: "Kolkata lies on the Hooghly river; Delhi lies on the Yamuna river." },
    { q: "Which one does not belong with the others?", options: ["Wheat", "Rice", "Maize", "Cotton"], answer: 3, explanation: "Wheat, Rice and Maize are food grain crops; Cotton is a fiber crop." },
    { q: "Which number does not belong with the others?", options: ["5", "7", "11", "15"], answer: 3, explanation: "5, 7 and 11 are prime numbers; 15 (= 3 × 5) is not." },
    { q: "Which one does not belong with the others?", options: ["Radio", "Television", "Telephone", "Newspaper"], answer: 3, explanation: "Radio, Television and Telephone are electronic communication devices; a Newspaper is print media." },
    { q: "If COURAGE is coded as DPVSBHF, how is VALOUR coded?", options: ["WBMPVS", "WBMPUS", "WBLPVS", "VBMPVS"], answer: 0, explanation: "Each letter shifts one place forward: V→W, A→B, L→M, O→P, U→V, R→S gives WBMPVS." },
    { q: "If each letter of LEADER is replaced by its position in the alphabet (A=1 ... Z=26) and the values are added, what is the total?", options: ["43", "44", "45", "46"], answer: 2, explanation: "L=12, E=5, A=1, D=4, E=5, R=18; their sum is 12+5+1+4+5+18 = 45." },
    { q: "In a code language, 'ka pi lo' means 'fruit is sweet', 'pi na' means 'sweet dish' and 'lo ma' means 'fruit juice'. What does 'ka' stand for?", options: ["is", "fruit", "sweet", "dish"], answer: 0, explanation: "Comparing 'pi na'/'sweet dish' shows pi=sweet and 'lo ma'/'fruit juice' shows lo=fruit, leaving ka to mean 'is'." },
    { q: "A is the wife of B. C is the son of A. D is the daughter of C. How is B related to D?", options: ["Grandfather", "Father", "Uncle", "Brother"], answer: 0, explanation: "C is B's son (via A), and D is C's daughter, making B the grandfather of D." },
    { q: "Pointing to a girl, Vikram said, \"She is the daughter of the only son of my father.\" How is the girl related to Vikram?", options: ["Daughter", "Sister", "Niece", "Cousin"], answer: 0, explanation: "The 'only son' of Vikram's father is Vikram himself, so the girl is his daughter." },
    { q: "A person walks 7 km east, then 5 km south, then 7 km west. How far and in which direction is he from the start?", options: ["5 km South", "5 km North", "19 km East", "12 km West"], answer: 0, explanation: "The 7 km east and 7 km west legs cancel out, leaving him 5 km south of the start." },
    { q: "Two men start from the same point. One walks 6 km north and the other 8 km east. What is the distance between them?", options: ["10 km", "12 km", "14 km", "2 km"], answer: 0, explanation: "The two paths form a right angle, so the distance is √(6²+8²) = √100 = 10 km." },
    { q: "In a class of 45 students, Ajay's rank from the top is 19th. What is his rank from the bottom?", options: ["26th", "27th", "28th", "25th"], answer: 1, explanation: "Rank from the bottom = total students − rank from top + 1 = 45−19+1 = 27." },
    { q: "Six people A to F sit in a row. E is at the left end and D at the right end. A is next to E. B is between A and C. F is between C and D. Who is 4th from the left?", options: ["B", "C", "F", "A"], answer: 1, explanation: "With E at position 1, D at 6, A next to E at 2, B between A and C, and F between C and D, the order is E-A-B-C-F-D, so C is 4th from the left." },
    { q: "8 men can build a wall in 12 days. How many days will 6 men take to build the same wall?", options: ["14", "16", "18", "9"], answer: 1, explanation: "Total work is 8×12 = 96 man-days; 6 men would need 96/6 = 16 days." },
    { q: "The average of 7 consecutive whole numbers is 20. What is the largest of them?", options: ["22", "23", "24", "26"], answer: 1, explanation: "Seven consecutive numbers averaging 20 run from 17 to 23, making 23 the largest." },
    { q: "What is the angle between the hands of a clock at 12:30?", options: ["150°", "165°", "180°", "175°"], answer: 1, explanation: "At 12:30 the hour hand is 15° past 12 and the minute hand is at 180° (the 6), a gap of 165°." },
    { q: "In a leap year, 1 January is a Sunday. How many Sundays are there in that year?", options: ["52", "53", "54", "51"], answer: 1, explanation: "366 days = 52 weeks plus 2 extra days (Jan 1 and Jan 2); since Jan 1 is a Sunday, that gives 53 Sundays." },
    { q: "Statements: No pilot is a sailor. All sailors are swimmers. Conclusions: I. No pilot is a swimmer. II. Some swimmers are not pilots.", options: ["Only I follows", "Only II follows", "Both follow", "Neither follows"], answer: 1, explanation: "Since all sailors are swimmers and no sailor is a pilot, those sailors are swimmers who aren't pilots, giving II; but pilots could still overlap with non-sailor swimmers, so I doesn't follow." },
    { q: "Statement: All employees must submit leave applications a week in advance. Assumptions: I. Leave applications are sometimes submitted late. II. No leave will be granted in an emergency.", options: ["Only I is implicit", "Only II is implicit", "Both are implicit", "Neither is implicit"], answer: 0, explanation: "A rule requiring advance notice implies it is sometimes not followed, making I implicit; the statement says nothing about emergencies, so II is not implicit." },
    { q: "A 5 × 5 × 5 cube is painted on all faces and cut into unit cubes. How many unit cubes have exactly two faces painted?", options: ["27", "36", "48", "54"], answer: 1, explanation: "Two-face-painted cubes lie along the edges, excluding corners: 12 edges × (5−2) = 36." },
    { q: "If the English alphabet is written in reverse order, how many letters stay in the same position as before?", options: ["0", "1", "2", "13"], answer: 0, explanation: "A letter at position i maps to position 27−i under reversal; i = 27−i has no integer solution, so no letter stays in place." },
    { q: "How many pairs of letters in the word SOLDIER have as many letters between them in the word as there are between them in the English alphabet?", options: ["None", "One", "Two", "Three"], answer: 0, explanation: "Checking every letter pair's word-gap against its alphabet-gap shows none match, so the answer is none." },
  ],
};

export default test;
