import type { Test } from "./index";

const test: Test = {
  id: "oir-6",
  title: "OIR Test 6",
  durationMinutes: 20,
  questions: [
    { q: "Find the next number: 8, 12, 20, 36, 68, ?", options: ["124", "132", "136", "140"], answer: 1, explanation: "The difference between terms doubles each time (4, 8, 16, 32, 64); 68+64 = 132." },
    { q: "Find the next number: 2, 9, 28, 65, 126, ?", options: ["215", "216", "217", "218"], answer: 2, explanation: "Each term equals n³+1 for n=1,2,3,...: 6³+1 = 217." },
    { q: "Find the next number: 1, 4, 10, 22, 46, ?", options: ["92", "94", "96", "98"], answer: 1, explanation: "Each term equals double the previous term plus 2: 46×2+2 = 94." },
    { q: "Find the next number: 3, 5, 9, 17, 33, ?", options: ["63", "65", "67", "69"], answer: 1, explanation: "Each term equals double the previous term minus 1: 33×2−1 = 65." },
    { q: "Find the next letter: A, B, D, G, K, ?", options: ["O", "P", "Q", "N"], answer: 1, explanation: "The gaps between letter positions grow by 1 each time (1, 2, 3, 4, 5): K (11th) + 5 = 16th letter, P." },
    { q: "Find the next group: ZYX, WVU, TSR, ?", options: ["QPO", "PON", "RQP", "QON"], answer: 0, explanation: "Each group is 3 consecutive descending letters starting 3 positions before the last group's start; after T-S-R comes Q-P-O." },
    { q: "Ship : Captain :: Aircraft : ?", options: ["Pilot", "Engineer", "Steward", "Officer"], answer: 0, explanation: "A Captain commands a ship; a Pilot commands (flies) an aircraft." },
    { q: "4 : 20 :: 6 : ?", options: ["30", "36", "42", "48"], answer: 2, explanation: "The relationship is n²+n: 4²+4 = 20, so 6²+6 = 42." },
    { q: "Botany : Plants :: Ichthyology : ?", options: ["Fish", "Insects", "Birds", "Reptiles"], answer: 0, explanation: "Botany is the study of plants; ichthyology is the study of fish." },
    { q: "Which one does not belong with the others?", options: ["Mercury", "Venus", "Moon", "Mars"], answer: 2, explanation: "Mercury, Venus and Mars are planets; the Moon is a satellite, not a planet." },
    { q: "Which number does not belong with the others?", options: ["2", "3", "5", "9"], answer: 3, explanation: "2, 3 and 5 are prime numbers; 9 (= 3×3) is not." },
    { q: "Which one does not belong with the others?", options: ["Arjun", "Bhishma", "Karna", "Akbar"], answer: 3, explanation: "Arjun, Bhishma and Karna are characters from the Mahabharata; Akbar is a historical Mughal emperor." },
    { q: "If HONEST is coded as GNMDRS, how is TRUTH coded?", options: ["SQTSG", "SQTTG", "SQUSG", "RQTSG"], answer: 0, explanation: "Each letter of the code shifts one place back in the alphabet (H→G, O→N, ...); applying the same shift to TRUTH gives SQTSG." },
    { q: "In a code language, 'pit nit dit' means 'come here now', 'nit sit' means 'here today' and 'dit bit' means 'now go'. What is the code for 'come'?", options: ["pit", "nit", "dit", "bit"], answer: 0, explanation: "'nit' is the common code for 'here' and 'dit' is the common code for 'now', leaving 'pit' as the code for 'come'." },
    { q: "If letters are valued by position (A=1 ... Z=26) so that MANGO totals 50, what is the total for GRAPE?", options: ["45", "46", "47", "48"], answer: 2, explanation: "Summing letter positions: G+R+A+P+E = 7+18+1+16+5 = 47." },
    { q: "A and B are brothers. C is the daughter of A. D is the son of C. How is D related to B?", options: ["Grand-nephew", "Nephew", "Grandson", "Cousin"], answer: 0, explanation: "C is A's daughter, making her B's niece, so D, C's son, is B's grand-nephew." },
    { q: "A man says, \"She is the wife of my father's wife's only son.\" How is the woman related to the man?", options: ["Wife", "Mother", "Sister-in-law", "Daughter"], answer: 0, explanation: "His father's wife is his mother, and her only son is the man himself, so the woman described is his own wife." },
    { q: "A man starts walking north, turns right, then right again, then left. Which direction is he facing now?", options: ["East", "West", "South", "North"], answer: 0, explanation: "North, right turn → East, right turn → South, left turn → East again." },
    { q: "A man walks 5 km east, turns left and walks 4 km, turns left and walks 5 km, then turns right and walks 2 km. How far and in which direction is he from the start?", options: ["6 km North", "4 km North", "6 km South", "2 km North"], answer: 0, explanation: "Plotting the path (5 km East, 4 km North, 5 km West, 2 km North) ends at a point 6 km due north of the start." },
    { q: "In a queue Arun is 10th from the front and Varun is 15th from the back. Arun is ahead of Varun and there are 3 people between them. How many people are in the queue?", options: ["26", "27", "28", "29"], answer: 2, explanation: "Varun is 10+3+1 = 14th from the front; total people = 14+15−1 = 28." },
    { q: "Five books P, Q, R, S, T are on a shelf. Q is at one end. R is between P and S. T is between Q and P. Which book is in the middle?", options: ["P", "R", "T", "S"], answer: 0, explanation: "The only order satisfying both conditions is Q, T, P, R, S, which places P in the middle position." },
    { q: "20% of a number is 45. What is 60% of the same number?", options: ["125", "135", "145", "155"], answer: 1, explanation: "20% = 45 means the number is 225, so 60% of 225 = 135." },
    { q: "An exam has 100 questions with +1 for each correct answer and −0.25 for each wrong one. A candidate attempts all questions and scores 75. How many did he answer correctly?", options: ["75", "80", "85", "90"], answer: 1, explanation: "With c correct: c − 0.25(100−c) = 75 gives 1.25c = 100, so c = 80." },
    { q: "By how many degrees does the minute hand of a clock gain on the hour hand every minute?", options: ["5°", "5.5°", "6°", "6.5°"], answer: 1, explanation: "The minute hand moves 6° per minute and the hour hand 0.5° per minute, a gain of 5.5° per minute." },
    { q: "In a non-leap year, how many days are there from 15 March to 15 August, both days included?", options: ["152", "153", "154", "155"], answer: 2, explanation: "Counting inclusively: 1 (Mar 15) + 16 (rest of Mar) + 30 (Apr) + 31 (May) + 30 (Jun) + 31 (Jul) + 15 (Aug) = 154 days." },
    { q: "Statements: Some officers are pilots. All pilots are brave. Conclusions: I. Some officers are brave. II. Some brave people are officers.", options: ["Only I follows", "Only II follows", "Both follow", "Neither follows"], answer: 2, explanation: "Since some officers are pilots and all pilots are brave, those officers are brave (I), and converting this particular statement gives some brave people are officers (II)." },
    { q: "Statement: Petrol prices have risen by 10% this month. Conclusions: I. Transport costs are likely to rise. II. People will stop buying cars.", options: ["Only I follows", "Only II follows", "Both follow", "Neither follows"], answer: 0, explanation: "A price rise plausibly pushes up transport costs (I), but a modest 10% rise doesn't reasonably imply people will stop buying cars altogether (II is too extreme)." },
    { q: "A cube painted green on all faces is cut into 125 equal small cubes. How many small cubes have exactly three faces painted?", options: ["8", "12", "27", "36"], answer: 0, explanation: "Only the 8 corner cubes of any painted cube touch three original faces, regardless of how many pieces it is divided into." },
    { q: "If A is written as Z, B as Y, C as X and so on, how is NDA written?", options: ["MWZ", "MXZ", "NWZ", "MWY"], answer: 0, explanation: "Each letter maps to (27 − its position): N(14)→M(13), D(4)→W(23), A(1)→Z(26), giving MWZ." },
    { q: "How many vowels are there in the word INTELLIGENCE?", options: ["4", "5", "6", "3"], answer: 1, explanation: "INTELLIGENCE contains the vowels I, E, I, E, E — five in total." },
  ],
};

export default test;
