import type { Test } from "./index";

const test: Test = {
  id: "oir-1",
  title: "OIR Test 1",
  durationMinutes: 20,
  questions: [
    { q: "Find the next number in the series: 3, 7, 15, 31, 63, ?", options: ["125", "127", "129", "131"], answer: 1 },
    { q: "Find the next number in the series: 2, 3, 5, 7, 11, 13, 17, ?", options: ["18", "19", "21", "23"], answer: 1 },
    { q: "Find the missing number: 1, 8, 27, 64, ?, 216", options: ["100", "125", "144", "150"], answer: 1 },
    { q: "Find the next number in the series: 5, 11, 23, 47, 95, ?", options: ["189", "190", "191", "192"], answer: 2 },
    { q: "Find the next letter in the series: A, C, F, J, O, ?", options: ["T", "U", "V", "W"], answer: 1 },
    { q: "Find the next letter in the series: Z, X, U, Q, ?", options: ["M", "L", "K", "J"], answer: 1 },
    { q: "Ornithology : Birds :: Entomology : ?", options: ["Fish", "Insects", "Plants", "Fossils"], answer: 1 },
    { q: "8 : 512 :: 6 : ?", options: ["36", "216", "196", "64"], answer: 1 },
    { q: "Brigadier : Brigade :: Lieutenant : ?", options: ["Section", "Platoon", "Company", "Battalion"], answer: 1 },
    { q: "Which one does not belong with the others?", options: ["Copper", "Iron", "Zinc", "Brass"], answer: 3 },
    { q: "Which number does not belong with the others?", options: ["17", "29", "37", "51"], answer: 3 },
    { q: "Which one does not belong with the others?", options: ["Tsunami", "Earthquake", "Hurricane", "Reservoir"], answer: 3 },
    { q: "If SOLDIER is written as TPMEJFS in a code, how is ARMY written in the same code?", options: ["BSNZ", "BSMZ", "BRNZ", "ASNZ"], answer: 0 },
    { q: "In a certain code ROSE is written as 6821, CHAIR as 73456 and PREACH as 961473. How is SEARCH written?", options: ["214673", "216473", "214763", "246173"], answer: 0 },
    { q: "If MADRAS is coded as NBESBT, how is BOMBAY coded?", options: ["CPNCBZ", "CPNCBY", "CPMCBZ", "DPNCBZ"], answer: 0 },
    { q: "A is B's sister. C is B's mother. D is C's father. E is D's mother. How is A related to D?", options: ["Grandmother", "Granddaughter", "Daughter", "Grandfather"], answer: 1 },
    { q: "Pointing to a photograph, a man said, \"I have no brother or sister, but that man's father is my father's son.\" Whose photograph is it?", options: ["His son", "His nephew", "His father", "His cousin"], answer: 0 },
    { q: "A man walks 5 km south, turns left and walks 3 km, turns left again and walks 5 km. How far and in which direction is he from his starting point?", options: ["3 km East", "3 km West", "8 km South", "13 km North"], answer: 0 },
    { q: "A man facing north turns 90° clockwise, then 180° anticlockwise, then 45° clockwise. Which direction is he facing now?", options: ["North-West", "North-East", "South-West", "West"], answer: 0 },
    { q: "In a row of 40 students, Rahul is 17th from the left and Amit is 12th from the right. How many students are between them?", options: ["10", "11", "12", "13"], answer: 1 },
    { q: "Sita is taller than Gita but shorter than Rita. Mita is taller than Rita. Who is the shortest?", options: ["Sita", "Gita", "Rita", "Mita"], answer: 1 },
    { q: "A train 150 m long passes a pole in 15 seconds. What is its speed in km/h?", options: ["30", "36", "40", "45"], answer: 1 },
    { q: "The sum of the ages of a father and son is 60 years. Six years ago the father was five times as old as the son. Their present ages are:", options: ["46 and 14", "45 and 15", "48 and 12", "50 and 10"], answer: 0 },
    { q: "How many times do the hands of a clock coincide in 24 hours?", options: ["24", "22", "12", "11"], answer: 1 },
    { q: "1 January 2024 was a Monday. What day of the week was 1 March 2024?", options: ["Thursday", "Friday", "Saturday", "Sunday"], answer: 1 },
    { q: "Statements: All soldiers are brave. Some brave people are officers. Conclusions: I. Some soldiers are officers. II. All officers are brave.", options: ["Only I follows", "Only II follows", "Both follow", "Neither follows"], answer: 3 },
    { q: "Statements: Some pens are pencils. All pencils are erasers. Conclusions: I. Some pens are erasers. II. All erasers are pencils.", options: ["Only I follows", "Only II follows", "Both follow", "Neither follows"], answer: 0 },
    { q: "A cube of side 4 cm is painted on all faces and cut into 1 cm cubes. How many small cubes have exactly two faces painted?", options: ["16", "24", "32", "48"], answer: 1 },
    { q: "Which letter is 7th to the right of the 11th letter from the left in the English alphabet?", options: ["Q", "R", "S", "T"], answer: 1 },
    { q: "In the word PROMOTION, each vowel is replaced by the next letter of the alphabet and each consonant by the previous letter. How many vowels are there in the new word?", options: ["0", "1", "2", "3"], answer: 1 },
  ],
};

export default test;
