import type { Test } from "./index";

const test: Test = {
  id: "oir-2",
  title: "OIR Test 2",
  durationMinutes: 20,
  questions: [
    { q: "Find the next number: 4, 9, 19, 39, 79, ?", options: ["149", "157", "159", "161"], answer: 2, explanation: "Each term equals double the previous term plus 1: 79×2+1 = 159." },
    { q: "Find the next number: 2, 5, 10, 17, 26, ?", options: ["35", "36", "37", "38"], answer: 2, explanation: "The differences between terms increase by 2 each time (3, 5, 7, 9); the next difference is 11, giving 26+11 = 37." },
    { q: "Find the next number: 100, 98, 94, 88, 80, ?", options: ["72", "70", "68", "66"], answer: 1, explanation: "The differences double in magnitude each time (−2, −4, −6, −8); the next difference is −10, giving 80−10 = 70." },
    { q: "Find the missing number: 1, 1, 2, 3, 5, 8, 13, ?, 34", options: ["20", "21", "22", "23"], answer: 1, explanation: "This is the Fibonacci sequence, each term the sum of the two before it: 13+8 = 21." },
    { q: "Find the next letter: B, E, H, K, N, ?", options: ["P", "Q", "R", "S"], answer: 1, explanation: "Letter positions increase by 3 each time (B=2, E=5, H=8, K=11, N=14); the next is 17, which is Q." },
    { q: "Find the next pair: AZ, BY, CX, DW, ?", options: ["EV", "EU", "FV", "EW"], answer: 0, explanation: "The first letter advances forward (A, B, C, D, E) while the second letter retreats (Z, Y, X, W, V), giving EV." },
    { q: "Sculptor : Statue :: Poet : ?", options: ["Pen", "Poem", "Rhyme", "Book"], answer: 1, explanation: "A sculptor's created work is a statue; a poet's created work is a poem." },
    { q: "7 : 50 :: 9 : ?", options: ["80", "81", "82", "90"], answer: 2, explanation: "The relationship is n²+1: 7²+1 = 50, so 9²+1 = 82." },
    { q: "Thermometer : Temperature :: Barometer : ?", options: ["Humidity", "Pressure", "Altitude", "Wind"], answer: 1, explanation: "A barometer is an instrument that measures atmospheric pressure." },
    { q: "Which one does not belong with the others?", options: ["Tiger", "Lion", "Leopard", "Wolf"], answer: 3, explanation: "Tiger, Lion and Leopard are big cats of the genus Panthera; Wolf is a canine." },
    { q: "Which number does not belong with the others?", options: ["121", "144", "169", "195"], answer: 3, explanation: "121, 144 and 169 are perfect squares (11², 12², 13²); 195 is not." },
    { q: "Which one does not belong with the others?", options: ["Tulsidas", "Kabir", "Surdas", "Tansen"], answer: 3, explanation: "Tulsidas, Kabir and Surdas were poet-saints; Tansen was a court musician, not a poet." },
    { q: "If FRIEND is coded as GSJFOE, how is ENEMY coded?", options: ["FOFNZ", "FOFMZ", "ENFNZ", "FNFNZ"], answer: 0, explanation: "Each letter shifts one place forward in the alphabet (F→G, R→S, etc.), so ENEMY becomes FOFNZ." },
    { q: "In a code language, 'sky is blue' is written as 'ta ra ma', 'blue is deep' as 'ma ra ka' and 'deep sea' as 'ka pa'. What is the code for 'sky'?", options: ["ta", "ra", "ma", "ka"], answer: 0, explanation: "'Is' and 'blue' are the words common to the first two statements and share the codes ra/ma, leaving 'ta' as the unique code for 'sky'." },
    { q: "In a code, ALPHA is written as ZOKSZ. How is DELTA written in the same code?", options: ["WVOGZ", "WVOHZ", "WUOGZ", "XVOGZ"], answer: 0, explanation: "Each letter maps to its mirror position in the alphabet (new = 27 − old): D→W, E→V, L→O, T→G, A→Z gives WVOGZ." },
    { q: "P is the brother of Q. R is the mother of P. S is the father of R. How is Q related to S?", options: ["Granddaughter", "Grandson", "Either grandson or granddaughter", "Niece"], answer: 2, explanation: "'Brother of Q' only fixes P's gender, not Q's, so Q — S's grandchild — could be either a grandson or a granddaughter." },
    { q: "Introducing a woman, a man said, \"She is the daughter of my grandfather's only son.\" How is the woman related to the man?", options: ["Sister", "Cousin", "Aunt", "Mother"], answer: 0, explanation: "'My grandfather's only son' must be the man's own father, so the woman, his father's daughter, is his sister." },
    { q: "Ram walks 10 m north, turns right and walks 5 m, turns right and walks 10 m, then turns left and walks 5 m. How far is he from the starting point?", options: ["5 m", "10 m", "15 m", "20 m"], answer: 1, explanation: "Plotting the path (10 m N, 5 m E, 10 m S, 5 m E) has the two north-south legs cancel out, leaving him 10 m east of the start." },
    { q: "At 6 am a man faces the rising sun. He turns right, walks some distance, then turns left. Which direction is he facing now?", options: ["East", "West", "North", "South"], answer: 0, explanation: "Facing the rising sun means facing East; turning right faces him South, then turning left brings him back to facing East." },
    { q: "Ravi ranks 12th from the top and 28th from the bottom in his class. How many students are in the class?", options: ["38", "39", "40", "41"], answer: 1, explanation: "Total students = (rank from top) + (rank from bottom) − 1 = 12+28−1 = 39." },
    { q: "A is older than B but younger than C. D is older than C. E is the youngest. Who is the second oldest?", options: ["A", "B", "C", "D"], answer: 2, explanation: "The order from oldest to youngest is D > C > A > B > E, so C is second oldest." },
    { q: "A can do a piece of work in 12 days and B in 24 days. In how many days can they finish it together?", options: ["6", "8", "9", "10"], answer: 1, explanation: "Combined rate = 1/12 + 1/24 = 1/8 of the work per day, so together they finish in 8 days." },
    { q: "Which is the smallest number that leaves a remainder of 3 when divided by 5 and a remainder of 4 when divided by 7?", options: ["13", "18", "23", "33"], answer: 1, explanation: "Testing numbers of the form 5k+3 (3, 8, 13, 18, ...) for a remainder of 4 when divided by 7, 18 is the first that works (18÷7 = 2 remainder 4)." },
    { q: "What is the angle between the hands of a clock at 4:20?", options: ["0°", "5°", "10°", "15°"], answer: 2, explanation: "Using |30H − 5.5M|: |30×4 − 5.5×20| = |120 − 110| = 10°." },
    { q: "If today is Wednesday, what day of the week will it be 100 days from today?", options: ["Thursday", "Friday", "Saturday", "Monday"], answer: 1, explanation: "100 days is 14 full weeks plus 2 days, so 100 mod 7 = 2; Wednesday + 2 days = Friday." },
    { q: "Statements: All pens are books. All books are chairs. Conclusions: I. All pens are chairs. II. Some chairs are pens.", options: ["Only I follows", "Only II follows", "Both follow", "Neither follows"], answer: 2, explanation: "All pens are books and all books are chairs, so all pens are chairs (I); since those pens exist within the chair set, some chairs are pens (II) — both follow." },
    { q: "Statement: An advertisement says, \"Use Brand X toothpaste for whiter teeth.\" Assumptions: I. People want whiter teeth. II. Brand X is the cheapest toothpaste.", options: ["Only I is implicit", "Only II is implicit", "Both are implicit", "Neither is implicit"], answer: 0, explanation: "The ad's appeal only makes sense if people want whiter teeth (I is implicit); it says nothing about price, so II does not follow." },
    { q: "A cube painted red on all faces is cut into 27 equal small cubes. How many small cubes have exactly one face painted?", options: ["6", "8", "12", "1"], answer: 0, explanation: "In a 3×3×3 cube, only the center cube of each face has exactly one painted side: 6 faces × 1 = 6." },
    { q: "If the English alphabet is written in reverse order, which letter will be 5th to the left of the 10th letter from the right?", options: ["E", "O", "N", "P"], answer: 1, explanation: "In the reversed alphabet (Z...A), the 10th letter from the right is J; counting 5 more places to the left from there lands on O." },
    { q: "If the letters of the word RECRUITMENT are arranged in alphabetical order, how many letters remain in the same position as in the original word?", options: ["0", "1", "2", "3"], answer: 1, explanation: "Sorting RECRUITMENT alphabetically (C,E,E,I,M,N,R,R,T,T,U) matches the original word only at position 2 (E), so exactly 1 letter stays in place." },
  ],
};

export default test;
