import type { Test } from "./index";

const test: Test = {
  id: "oir-4",
  title: "OIR Test 4",
  durationMinutes: 20,
  questions: [
    { q: "Find the next number: 7, 10, 16, 28, 52, ?", options: ["96", "100", "104", "108"], answer: 1, explanation: "Each difference doubles the previous one (3, 6, 12, 24, 48): 52+48 = 100." },
    { q: "Find the next number: 1, 3, 7, 13, 21, ?", options: ["29", "31", "33", "35"], answer: 1, explanation: "Differences increase by 2 each time (2, 4, 6, 8, 10): 21+10 = 31." },
    { q: "Find the next number: 4, 12, 36, 108, ?", options: ["216", "324", "432", "648"], answer: 1, explanation: "Each term is multiplied by 3: 108×3 = 324." },
    { q: "Find the next number: 13, 17, 19, 23, 29, ?", options: ["30", "31", "33", "37"], answer: 1, explanation: "The series lists consecutive prime numbers; the next prime after 29 is 31." },
    { q: "Find the next letter: D, H, L, P, ?", options: ["S", "T", "U", "V"], answer: 1, explanation: "Each letter jumps 4 positions ahead: D(4), H(8), L(12), P(16), so next is T(20)." },
    { q: "Find the next pair: AB, DE, GH, JK, ?", options: ["LM", "MN", "NO", "KL"], answer: 1, explanation: "Starting letters increase by 3 each time (A, D, G, J, M), giving the pair MN." },
    { q: "Chisel : Sculptor :: Scalpel : ?", options: ["Doctor", "Surgeon", "Butcher", "Barber"], answer: 1, explanation: "A sculptor's primary tool is the chisel, just as a surgeon's is the scalpel." },
    { q: "9 : 80 :: 11 : ?", options: ["110", "120", "121", "132"], answer: 1, explanation: "The relationship is n²−1: 9²−1 = 80, so 11²−1 = 120." },
    { q: "Lieutenant Colonel : Battalion :: Major General : ?", options: ["Brigade", "Division", "Corps", "Command"], answer: 1, explanation: "A Lieutenant Colonel commands a Battalion, just as a Major General commands a Division." },
    { q: "Which one does not belong with the others?", options: ["Cheetah", "Deer", "Horse", "Snail"], answer: 3, explanation: "Cheetah, Deer and Horse are fast-running animals; a Snail is extremely slow." },
    { q: "Which number does not belong with the others?", options: ["4", "9", "16", "27"], answer: 3, explanation: "4, 9 and 16 are perfect squares (2², 3², 4²); 27 is a cube (3³), not a square." },
    { q: "Which one does not belong with the others?", options: ["Violin", "Flute", "Guitar", "Sitar"], answer: 1, explanation: "Violin, Guitar and Sitar are string instruments; Flute is a wind instrument." },
    { q: "If MOBILE is coded as OQDKNG, how is LAPTOP coded?", options: ["NCRVQR", "NCRVQP", "MCRVQR", "NBRVQR"], answer: 0, explanation: "Each letter shifts 2 places forward in the alphabet: L→N, A→C, P→R, T→V, O→Q, P→R gives NCRVQR." },
    { q: "If TEACHER is written as VGCEJGT in a code, how is STUDENT written?", options: ["UVWFGPV", "UVWFGPU", "UVXFGPV", "TVWFGPV"], answer: 0, explanation: "Each letter shifts 2 places forward in the alphabet: S→U, T→V, U→W, D→F, E→G, N→P, T→V gives UVWFGPV." },
    { q: "In a code, 7 means '×', 5 means '+', 3 means '−' and 1 means '÷'. What is the value of 8 7 4 5 6 3 2?", options: ["32", "36", "38", "40"], answer: 1, explanation: "Substituting the symbols gives 8×4+6−2 = 32+6−2 = 36." },
    { q: "A is the son of B. B is the sister of C. D is the father of C. How is A related to D?", options: ["Grandson", "Nephew", "Son", "Brother"], answer: 0, explanation: "Since B is C's sister, D (C's father) is also B's father; A, B's son, is therefore D's grandson." },
    { q: "A woman says, \"The man in this photo is the husband of my mother's only daughter.\" How is the man related to the woman?", options: ["Husband", "Brother", "Father", "Son"], answer: 0, explanation: "Her mother's only daughter is the woman herself, so the man described is her own husband." },
    { q: "A man walks 3 km north, 4 km east, 3 km north and 4 km east. How far is he from his starting point?", options: ["10 km", "12 km", "14 km", "7 km"], answer: 0, explanation: "Net displacement is 6 km north and 8 km east; by Pythagoras, distance = √(6²+8²) = 10 km." },
    { q: "At 3 pm a man notices that his shadow falls to his right. Which direction is he facing?", options: ["North", "South", "East", "West"], answer: 0, explanation: "At 3 pm the sun is in the west; facing North, the sun is to his left, so his shadow falls opposite it, to his right, in the east." },
    { q: "In a row of 25 girls, Priya is 10th from the left. Sonia is 6th to the right of Priya. What is Sonia's position from the right end?", options: ["9th", "10th", "11th", "12th"], answer: 1, explanation: "Sonia's position from the left is 10+6 = 16th; her position from the right is 25−16+1 = 10th." },
    { q: "Six boxes are stacked. F is at the top and E at the bottom. A is directly above B, B is directly above D, and C is directly below D. Which box is 3rd from the top?", options: ["A", "B", "D", "C"], answer: 1, explanation: "The stack from top to bottom is F, A, B, D, C, E, so the 3rd box from the top is B." },
    { q: "A shopkeeper marks his goods 20% above cost price and allows a 10% discount. What is his profit percentage?", options: ["8%", "10%", "12%", "2%"], answer: 0, explanation: "With cost price 100, the marked price is 120; a 10% discount gives a selling price of 108, an 8% profit." },
    { q: "The product of two numbers is 120 and their sum is 23. What is the larger number?", options: ["12", "15", "20", "24"], answer: 1, explanation: "Solving x+y=23 and xy=120 gives x=15 and y=8, so the larger number is 15." },
    { q: "What is the angle between the hands of a clock at 7:30?", options: ["30°", "45°", "60°", "75°"], answer: 1, explanation: "At 7:30 the hour hand is at 225° (7×30°+15°) and the minute hand at 180°, a difference of 45°." },
    { q: "In a non-leap year, 3 March is a Tuesday. What day of the week is 3 April?", options: ["Thursday", "Friday", "Saturday", "Sunday"], answer: 1, explanation: "March has 31 days, so 3 April is 31 days after 3 March; 31 mod 7 = 3, so Tuesday + 3 days = Friday." },
    { q: "Statements: No soldier is a coward. All cowards are weak. Conclusions: I. No soldier is weak. II. Some weak people are cowards.", options: ["Only I follows", "Only II follows", "Both follow", "Neither follows"], answer: 1, explanation: "'All cowards are weak' converts to 'some weak people are cowards' (II), but the first statement says nothing about soldiers being weak, so I does not follow." },
    { q: "Statement: \"Report to the office by 9 am,\" the manager told the staff. Assumptions: I. The staff are able to reach the office by 9 am. II. The staff usually come late.", options: ["Only I is implicit", "Only II is implicit", "Both are implicit", "Neither is implicit"], answer: 0, explanation: "Giving the instruction assumes the staff can comply (I); it does not imply they are usually late (II)." },
    { q: "A cube has each pair of opposite faces painted the same colour: red, blue and green. It is cut into 64 small cubes. How many small cubes have exactly two painted faces, one red and one blue?", options: ["4", "8", "12", "16"], answer: 1, explanation: "In the 4×4×4 cube, each of the 4 red–blue edges holds 2 non-corner cubes with exactly two painted faces: 4×2 = 8." },
    { q: "Every alternate letter starting from B is deleted from the English alphabet. Which letter is 8th from the left in the remaining letters?", options: ["M", "O", "Q", "K"], answer: 1, explanation: "Deleting every alternate letter from B leaves A, C, E, G, I, K, M, O, ...; the 8th letter in this sequence is O." },
    { q: "How many meaningful English words can be formed using all the letters of RAT, each exactly once?", options: ["2", "3", "4", "1"], answer: 1, explanation: "The letters R, A, T form three meaningful words: RAT, ART and TAR." },
  ],
};

export default test;
