import type { Test } from "./index";

const test: Test = {
  id: "oir-5",
  title: "OIR Test 5",
  durationMinutes: 20,
  questions: [
    { q: "Find the next number: 5, 9, 17, 33, 65, ?", options: ["127", "129", "131", "133"], answer: 1, explanation: "Each term is double the previous term minus 1: 65×2−1 = 129." },
    { q: "Find the next number: 1, 2, 6, 24, 120, ?", options: ["600", "720", "840", "960"], answer: 1, explanation: "The series is factorials of consecutive integers (1!, 2!, 3!, ...); the next term is 6! = 720." },
    { q: "Find the next number: 11, 13, 17, 25, 41, ?", options: ["65", "73", "81", "89"], answer: 1, explanation: "The gap between terms doubles each time (2, 4, 8, 16, 32), so 41 + 32 = 73." },
    { q: "Find the next number: 64, 32, 48, 24, 36, 18, ?", options: ["9", "27", "36", "54"], answer: 1, explanation: "The series alternates dividing by 2 and multiplying by 1.5: 18×1.5 = 27." },
    { q: "Find the next letter: A, D, I, P, ?", options: ["X", "Y", "Z", "W"], answer: 1, explanation: "Letter positions follow perfect squares (1, 4, 9, 16, 25); the 25th letter is Y." },
    { q: "Find the next pair: BD, FH, JL, NP, ?", options: ["QS", "RT", "ST", "RS"], answer: 1, explanation: "Both letters in each pair advance by 4 positions (B,F,J,N,R and D,H,L,P,T), giving RT." },
    { q: "Melt : Liquid :: Freeze : ?", options: ["Ice", "Solid", "Cold", "Water"], answer: 1, explanation: "Melting turns a solid into a liquid, so by the same relation, freezing turns a liquid into a solid." },
    { q: "16 : 4 :: 49 : ?", options: ["6", "7", "8", "9"], answer: 1, explanation: "The relationship is a square root: √16 = 4, so √49 = 7." },
    { q: "Navy : Admiral :: Air Force : ?", options: ["General", "Air Chief Marshal", "Commodore", "Field Marshal"], answer: 1, explanation: "Admiral is the highest rank in the Navy; the equivalent top rank in the Air Force is Air Chief Marshal." },
    { q: "Which one does not belong with the others?", options: ["Rose", "Lotus", "Marigold", "Neem"], answer: 3, explanation: "Rose, Lotus and Marigold are flowers; Neem is a tree." },
    { q: "Which number does not belong with the others?", options: ["27", "64", "125", "144"], answer: 3, explanation: "27, 64 and 125 are perfect cubes (3³, 4³, 5³); 144 is not a cube." },
    { q: "Which one does not belong with the others?", options: ["Kilogram", "Litre", "Metre", "Thermometer"], answer: 3, explanation: "Kilogram, Litre and Metre are units of measurement; a Thermometer is a measuring instrument, not a unit." },
    { q: "If WATER is coded as XBUFS, how is FIRE coded?", options: ["GJSF", "GJSE", "GISF", "HJSF"], answer: 0, explanation: "Each letter of WATER is shifted one place forward in the alphabet; applying the same +1 shift to FIRE gives GJSF." },
    { q: "If BRIGADE is written as EDAGIRB, how is COMMAND written in the same code?", options: ["DNAMMOC", "DNAMOMC", "DNAMMCO", "CNAMMOD"], answer: 0, explanation: "The code simply reverses the letters of the word; reversing COMMAND gives DNAMMOC." },
    { q: "If A=1, B=2, ..., Z=26, what is the sum of the letter values of the word NDA?", options: ["18", "19", "20", "21"], answer: 1, explanation: "N=14, D=4, A=1; their sum is 14+4+1 = 19." },
    { q: "M is the father of N. N is the sister of O. O is the son of P. How is P related to M?", options: ["Wife", "Sister", "Mother", "Daughter"], answer: 0, explanation: "N and O are siblings whose father is M; since O's other parent is P and M is male, P must be the mother, i.e., M's wife." },
    { q: "Pointing to a lady, Ramesh said, \"Her father's only son is my father.\" How is the lady related to Ramesh?", options: ["Aunt", "Mother", "Sister", "Cousin"], answer: 0, explanation: "The lady's father's only son is Ramesh's father, so the lady shares that same father — making her Ramesh's father's sister, i.e., his aunt." },
    { q: "A man walks 15 m north, then 10 m west, then 15 m south. How far and in which direction is he from his starting point?", options: ["10 m West", "10 m East", "25 m North", "40 m South"], answer: 0, explanation: "The final 15 m south exactly cancels the initial 15 m north, leaving only the 10 m walked west of the start." },
    { q: "If South-East becomes North, then North-East becomes:", options: ["West", "East", "South", "North-West"], answer: 0, explanation: "Rotating each direction three places counter-clockwise turns South-East into North; applying the same rotation to North-East gives West." },
    { q: "P is heavier than Q. R is lighter than S. Q is heavier than S. Who is the lightest?", options: ["P", "Q", "R", "S"], answer: 2, explanation: "Combining the inequalities gives P > Q > S > R, so R is the lightest." },
    { q: "Manoj is 14th from the top and 19th from the bottom in his class. How many students are in the class?", options: ["31", "32", "33", "34"], answer: 1, explanation: "Total students = (position from top) + (position from bottom) − 1 = 14 + 19 − 1 = 32." },
    { q: "A car travels at 60 km/h for 2 hours and then at 40 km/h for 3 hours. What is its average speed for the whole journey?", options: ["45 km/h", "48 km/h", "50 km/h", "52 km/h"], answer: 1, explanation: "Average speed = total distance ÷ total time = (60×2 + 40×3) / (2+3) = 240/5 = 48 km/h." },
    { q: "The sum of three consecutive odd numbers is 63. What is the largest of them?", options: ["21", "23", "25", "19"], answer: 1, explanation: "For consecutive odd numbers x−2, x, x+2 summing to 63, x = 21, so the largest is 23." },
    { q: "How many times in 12 hours are the hands of a clock at right angles?", options: ["11", "22", "24", "44"], answer: 1, explanation: "The hands form a right angle twice per hour on average, but two occurrences are skipped near the 3 and 9 o'clock hours, giving 22 times in 12 hours." },
    { q: "29 February 2024 was a Thursday. What day of the week is 29 February 2028?", options: ["Monday", "Tuesday", "Wednesday", "Thursday"], answer: 1, explanation: "From 29 Feb 2024 to 29 Feb 2028 is 1461 days; 1461 mod 7 = 5, so the day advances from Thursday to Tuesday." },
    { q: "Statements: All roses are flowers. Some flowers fade quickly. Conclusions: I. Some roses fade quickly. II. All flowers are roses.", options: ["Only I follows", "Only II follows", "Both follow", "Neither follows"], answer: 3, explanation: "Since only 'some' flowers fade quickly, those need not be roses, and 'some flowers fade' can't imply 'all flowers are roses' — neither conclusion is guaranteed." },
    { q: "Statement: Many students failed the entrance test. Courses of action: I. The test should be made easier. II. Students should be given better guidance.", options: ["Only I follows", "Only II follows", "Both follow", "Neither follows"], answer: 1, explanation: "Lowering the test's difficulty doesn't address why students failed, but better guidance is a constructive corrective action, so only II follows." },
    { q: "A cube of side 3 cm is painted on two adjacent faces only and then cut into 27 small cubes. How many small cubes have no paint on them?", options: ["12", "15", "18", "9"], answer: 0, explanation: "With the two painted faces at x=3 and y=3, unpainted cubes need x,y∈{1,2} and any z∈{1,2,3}, giving 2×2×3 = 12." },
    { q: "Which letter is exactly midway between J and T in the English alphabet?", options: ["N", "O", "P", "M"], answer: 1, explanation: "J is the 10th letter and T is the 20th; their midpoint is the 15th letter, O." },
    { q: "In the word TRANSPORT, the 1st and 2nd letters are interchanged, the 3rd and 4th, the 5th and 6th, and the 7th and 8th. Which letter is 5th from the right in the new arrangement?", options: ["P", "S", "A", "N"], answer: 0, explanation: "Swapping each adjacent pair turns TRANSPORT into R,T,N,A,P,S,R,O,T; counting 5 places from the right lands on P." },
  ],
};

export default test;
